# Generated by Django 4.2.7 on 2023-11-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(
                default="", height_field=180, upload_to="services", width_field=180
            ),
            preserve_default=False,
        ),
    ]
